apiVersion: v1
kind: Secret
metadata:
  name: freelance-secrets
  namespace: freelance-marketplace
type: Opaque
stringData:
  JWT_SECRET: "super-secret-key"
  STRIPE_SECRET_KEY: "sk_test_..."
  MINIO_ACCESS_KEY: "admin"
  MINIO_SECRET_KEY: "password"
  EMAIL_USER: "user@example.com"
  EMAIL_PASS: "password"
